# Keyword spotting fragment
# Usage: west build ... -- -DEXTRA_CONF_FILE=kws.conf
CONFIG_APP_KWS=y

# C++ support required by the Edge Impulse SDK
CONFIG_CPP=y
CONFIG_GLIBCXX_LIBCPP=y

CONFIG_EDGE_IMPULSE_SDK=y
