# WAV recording fragment
# Usage: west build ... -- -DEXTRA_CONF_FILE=rec.conf
CONFIG_APP_REC=y

# Flash partition map and page-layout info (required by the disk driver)
CONFIG_FLASH_MAP=y
CONFIG_FLASH_PAGE_LAYOUT=y

# Expose the QSPI flash partition as a USB-MSC block device
CONFIG_DISK_DRIVER_FLASH=y
CONFIG_USBD_MSC_CLASS=y

# FAT filesystem on the QSPI flash
CONFIG_FILE_SYSTEM=y
CONFIG_FAT_FILESYSTEM_ELM=y
CONFIG_FS_FATFS_MOUNT_MKFS=y
CONFIG_FS_FATFS_EXTRA_NATIVE_API=y
